#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : wcslib
Version  : 7.4
Release  : 12
URL      : ftp://ftp.atnf.csiro.au/pub/software/wcslib/wcslib-7.4.tar.bz2
Source0  : ftp://ftp.atnf.csiro.au/pub/software/wcslib/wcslib-7.4.tar.bz2
Summary  : An implementation of the FITS World Coordinate System standard
Group    : Development/Tools
License  : GPL-3.0 LGPL-3.0
Requires: wcslib-bin = %{version}-%{release}
Requires: wcslib-lib = %{version}-%{release}
Requires: wcslib-license = %{version}-%{release}
Requires: wcslib-man = %{version}-%{release}
BuildRequires : cfitsio-dev
BuildRequires : flex
BuildRequires : gfortran
BuildRequires : pkgconfig(x11)

%description
------------------------------------------------------------------------------
WCSLIB 7.4 and PGSBOX 7.4
------------------------------------------------------------------------------
WCSLIB 7.4 - an implementation of the FITS WCS standard.

%package bin
Summary: bin components for the wcslib package.
Group: Binaries
Requires: wcslib-license = %{version}-%{release}

%description bin
bin components for the wcslib package.


%package dev
Summary: dev components for the wcslib package.
Group: Development
Requires: wcslib-lib = %{version}-%{release}
Requires: wcslib-bin = %{version}-%{release}
Provides: wcslib-devel = %{version}-%{release}
Requires: wcslib = %{version}-%{release}

%description dev
dev components for the wcslib package.


%package doc
Summary: doc components for the wcslib package.
Group: Documentation
Requires: wcslib-man = %{version}-%{release}

%description doc
doc components for the wcslib package.


%package lib
Summary: lib components for the wcslib package.
Group: Libraries
Requires: wcslib-license = %{version}-%{release}

%description lib
lib components for the wcslib package.


%package license
Summary: license components for the wcslib package.
Group: Default

%description license
license components for the wcslib package.


%package man
Summary: man components for the wcslib package.
Group: Default

%description man
man components for the wcslib package.


%prep
%setup -q -n wcslib-7.4
cd %{_builddir}/wcslib-7.4

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1612216072
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$FFLAGS -fno-lto "
export FFLAGS="$FFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
%configure --disable-static
make  %{?_smp_mflags}

%install
export SOURCE_DATE_EPOCH=1612216072
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/wcslib
cp %{_builddir}/wcslib-7.4/COPYING %{buildroot}/usr/share/package-licenses/wcslib/8624bcdae55baeef00cd11d5dfcfa60f68710a02
cp %{_builddir}/wcslib-7.4/COPYING.LESSER %{buildroot}/usr/share/package-licenses/wcslib/e203d4ef09d404fa5c03cf6590e44231665be689
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/HPXcvt
/usr/bin/fitshdr
/usr/bin/wcsware

%files dev
%defattr(-,root,root,-)
/usr/include/wcslib
/usr/include/wcslib-7.4/cel.h
/usr/include/wcslib-7.4/cel.inc
/usr/include/wcslib-7.4/dis.h
/usr/include/wcslib-7.4/dis.inc
/usr/include/wcslib-7.4/fitshdr.h
/usr/include/wcslib-7.4/fitshdr.inc
/usr/include/wcslib-7.4/getwcstab.h
/usr/include/wcslib-7.4/getwcstab.inc
/usr/include/wcslib-7.4/lin.h
/usr/include/wcslib-7.4/lin.inc
/usr/include/wcslib-7.4/log.h
/usr/include/wcslib-7.4/log.inc
/usr/include/wcslib-7.4/prj.h
/usr/include/wcslib-7.4/prj.inc
/usr/include/wcslib-7.4/spc.h
/usr/include/wcslib-7.4/spc.inc
/usr/include/wcslib-7.4/sph.h
/usr/include/wcslib-7.4/sph.inc
/usr/include/wcslib-7.4/spx.h
/usr/include/wcslib-7.4/spx.inc
/usr/include/wcslib-7.4/tab.h
/usr/include/wcslib-7.4/tab.inc
/usr/include/wcslib-7.4/wcs.h
/usr/include/wcslib-7.4/wcs.inc
/usr/include/wcslib-7.4/wcsconfig.h
/usr/include/wcslib-7.4/wcsconfig_f77.h
/usr/include/wcslib-7.4/wcserr.h
/usr/include/wcslib-7.4/wcserr.inc
/usr/include/wcslib-7.4/wcsfix.h
/usr/include/wcslib-7.4/wcsfix.inc
/usr/include/wcslib-7.4/wcshdr.h
/usr/include/wcslib-7.4/wcshdr.inc
/usr/include/wcslib-7.4/wcslib.h
/usr/include/wcslib-7.4/wcsmath.h
/usr/include/wcslib-7.4/wcsmath.inc
/usr/include/wcslib-7.4/wcsprintf.h
/usr/include/wcslib-7.4/wcstrig.h
/usr/include/wcslib-7.4/wcsunits.h
/usr/include/wcslib-7.4/wcsunits.inc
/usr/include/wcslib-7.4/wcsutil.h
/usr/include/wcslib-7.4/wtbarr.h
/usr/lib64/libwcs.so
/usr/lib64/pkgconfig/wcslib.pc

%files doc
%defattr(0644,root,root,0755)
%doc /usr/share/doc/wcslib/*

%files lib
%defattr(-,root,root,-)
/usr/lib64/libwcs.so.7
/usr/lib64/libwcs.so.7.4

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/wcslib/8624bcdae55baeef00cd11d5dfcfa60f68710a02
/usr/share/package-licenses/wcslib/e203d4ef09d404fa5c03cf6590e44231665be689

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/HPXcvt.1
/usr/share/man/man1/fitshdr.1
/usr/share/man/man1/wcsware.1
