#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : wcslib
Version  : 6.2
Release  : 2
URL      : ftp://ftp.atnf.csiro.au/pub/software/wcslib/wcslib-6.2.tar.bz2
Source0  : ftp://ftp.atnf.csiro.au/pub/software/wcslib/wcslib-6.2.tar.bz2
Summary  : An implementation of the FITS World Coordinate System standard
Group    : Development/Tools
License  : GPL-3.0 LGPL-3.0
Requires: wcslib-bin = %{version}-%{release}
Requires: wcslib-lib = %{version}-%{release}
Requires: wcslib-license = %{version}-%{release}
Requires: wcslib-man = %{version}-%{release}
BuildRequires : cfitsio-dev
BuildRequires : flex
BuildRequires : gfortran
BuildRequires : pkgconfig(x11)

%description
------------------------------------------------------------------------------
WCSLIB 6.2 and PGSBOX 6.2
------------------------------------------------------------------------------
WCSLIB 6.2 - an implementation of the FITS WCS standard.

%package bin
Summary: bin components for the wcslib package.
Group: Binaries
Requires: wcslib-license = %{version}-%{release}
Requires: wcslib-man = %{version}-%{release}

%description bin
bin components for the wcslib package.


%package dev
Summary: dev components for the wcslib package.
Group: Development
Requires: wcslib-lib = %{version}-%{release}
Requires: wcslib-bin = %{version}-%{release}
Provides: wcslib-devel = %{version}-%{release}

%description dev
dev components for the wcslib package.


%package doc
Summary: doc components for the wcslib package.
Group: Documentation
Requires: wcslib-man = %{version}-%{release}

%description doc
doc components for the wcslib package.


%package lib
Summary: lib components for the wcslib package.
Group: Libraries
Requires: wcslib-license = %{version}-%{release}

%description lib
lib components for the wcslib package.


%package license
Summary: license components for the wcslib package.
Group: Default

%description license
license components for the wcslib package.


%package man
Summary: man components for the wcslib package.
Group: Default

%description man
man components for the wcslib package.


%prep
%setup -q -n wcslib-6.2

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1548186081
%configure --disable-static
make  %{?_smp_mflags}

%install
export SOURCE_DATE_EPOCH=1548186081
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/wcslib
cp COPYING %{buildroot}/usr/share/package-licenses/wcslib/COPYING
cp COPYING.LESSER %{buildroot}/usr/share/package-licenses/wcslib/COPYING.LESSER
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/HPXcvt
/usr/bin/fitshdr
/usr/bin/wcsware

%files dev
%defattr(-,root,root,-)
/usr/include/wcslib
/usr/include/wcslib-6.2/cel.h
/usr/include/wcslib-6.2/cel.inc
/usr/include/wcslib-6.2/dis.h
/usr/include/wcslib-6.2/dis.inc
/usr/include/wcslib-6.2/fitshdr.h
/usr/include/wcslib-6.2/fitshdr.inc
/usr/include/wcslib-6.2/getwcstab.h
/usr/include/wcslib-6.2/getwcstab.inc
/usr/include/wcslib-6.2/lin.h
/usr/include/wcslib-6.2/lin.inc
/usr/include/wcslib-6.2/log.h
/usr/include/wcslib-6.2/log.inc
/usr/include/wcslib-6.2/prj.h
/usr/include/wcslib-6.2/prj.inc
/usr/include/wcslib-6.2/spc.h
/usr/include/wcslib-6.2/spc.inc
/usr/include/wcslib-6.2/sph.h
/usr/include/wcslib-6.2/sph.inc
/usr/include/wcslib-6.2/spx.h
/usr/include/wcslib-6.2/spx.inc
/usr/include/wcslib-6.2/tab.h
/usr/include/wcslib-6.2/tab.inc
/usr/include/wcslib-6.2/wcs.h
/usr/include/wcslib-6.2/wcs.inc
/usr/include/wcslib-6.2/wcsconfig.h
/usr/include/wcslib-6.2/wcsconfig_f77.h
/usr/include/wcslib-6.2/wcserr.h
/usr/include/wcslib-6.2/wcserr.inc
/usr/include/wcslib-6.2/wcsfix.h
/usr/include/wcslib-6.2/wcsfix.inc
/usr/include/wcslib-6.2/wcshdr.h
/usr/include/wcslib-6.2/wcshdr.inc
/usr/include/wcslib-6.2/wcslib.h
/usr/include/wcslib-6.2/wcsmath.h
/usr/include/wcslib-6.2/wcsmath.inc
/usr/include/wcslib-6.2/wcsprintf.h
/usr/include/wcslib-6.2/wcstrig.h
/usr/include/wcslib-6.2/wcsunits.h
/usr/include/wcslib-6.2/wcsunits.inc
/usr/include/wcslib-6.2/wcsutil.h
/usr/include/wcslib-6.2/wtbarr.h
/usr/lib64/libwcs.so
/usr/lib64/pkgconfig/wcslib.pc

%files doc
%defattr(0644,root,root,0755)
%doc /usr/share/doc/wcslib/*

%files lib
%defattr(-,root,root,-)
/usr/lib64/libwcs.so.6
/usr/lib64/libwcs.so.6.2

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/wcslib/COPYING
/usr/share/package-licenses/wcslib/COPYING.LESSER

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/HPXcvt.1
/usr/share/man/man1/fitshdr.1
/usr/share/man/man1/wcsware.1
